// Code generated by hertz generator.

package Example

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _h2methodMw() []app.HandlerFunc {
	// your code...

	return nil
}

func __ddmethodMw() []app.HandlerFunc {
	// your code...
	ret := func(ctx context.Context, c *app.RequestContext) {
		fmt.Println("before add method")
		c.Next(ctx)
		fmt.Println("afger sdd method")
	}
	return []app.HandlerFunc{ret}

}

func _submethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getitemmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _redisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _redisquerymethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _redissetmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getitemdetailmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
