// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"ttidl1/biz/dal/db"
	"ttidl1/biz/dal/redis"
	"ttidl1/util"
)

func main() {
	h := server.Default()
	h.Use(util.MidShowMethodCostTime())
	//h.Use(util.MidRecover())
	h.Use(recovery.Recovery())
	_ = db.GetMongoClient()
	_ = redis.GetRedisClient()
	register(h)
	h.Spin()
}
