// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package redis

import (
	"ttidl1/conf"
)

// Injectors from wire.go:

func GetRedisClient() RedisClient {
	configServer := conf.NewServerConf()
	redisRedisClient := NewRedisClient(configServer)
	return redisRedisClient
}
