// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http_model

import (
	"ttidl1/conf"
)

// Injectors from wire.go:

func GetGemserverModel() GemserverModel {
	configServer := conf.NewServerConf()
	gemserverModel := NewGemserverModel(configServer)
	return gemserverModel
}
