// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package db

import (
	"ttidl1/conf"
)

// Injectors from wire.go:

func GetMongoClient() MongoClient {
	configServer := conf.NewServerConf()
	dbMongoClient := NewMongoClient(configServer)
	return dbMongoClient
}
