// Code generated by hertz generator.

package example

import (
	"context"
	"fmt"
	"ttidl1/util"

	"github.com/cloudwego/hertz/pkg/app"
	example "ttidl1/biz/model/h2/example"
)

// AddMethod .
// @router /add [GET]
func AddMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.AddReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(example.AddResp)
	resp.Ans = req.X / req.Y
	util.WriteResponse(c, resp)
	//c.JSON(200, resp)
}

// SubMethod .
// @router /post [POST]
func SubMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.AddReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(example.AddResp)
	if req.Y == 0 {
		c.AbortWithError(400, util.NewError(400, -1, "integer divide by zero!!!!!"))
		return
	}
	resp.Ans = req.X / req.Y
	r, err := util.StructToMap(resp, "", "")
	fmt.Println(r)

	c.JSON(200, resp)
}
