// Code generated by hertz generator.

package example

import (
	"context"
	"fmt"
	"github.com/bytedance/gopkg/util/logger"
	"github.com/cloudwego/hertz/pkg/app"
	example "ttidl1/biz/model/h2/example"
	"ttidl1/util"
)

// H2Method .
// @router /test [GET]
func H2Method(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.H2Req
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	logger.Info(req)
	resp := new(example.H2Resp)
	resp.RespBody = fmt.Sprintf("rep: %s", req.Name)
	rt, err := util.StructToMap(resp, "json", "")

	fmt.Println(rt)
	c.JSON(200, resp)
	//util.WriteResponse(c, resp)
}
