// Code generated by hertz generator.

package example

import (
	"context"
	"fmt"
	"github.com/goccy/go-json"
	"gopkg.in/mgo.v2/bson"
	"ttidl1/biz/dal/db/model"
	"ttidl1/util"

	"github.com/cloudwego/hertz/pkg/app"
	example "ttidl1/biz/model/h2/example"
)

// GetItemMethod .
// @router get_item [GET]
func GetItemMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.ItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	fmt.Println(req.GetSubject(), req.GetItemID())
	subject := req.GetSubject()
	item_id := bson.ObjectIdHex(req.GetItemID())
	dbItemModel := model.GetItemDbModel()
	t := dbItemModel.FindOneById(subject, item_id)
	s := new(example.ItemResp)
	fmt.Println("\n\n\n")
	fmt.Println(s)
	fmt.Println(t)

	s.Item = new(example.Item)
	s.Item.Data = new(example.Data)
	//s.Item.Data.Qs = make([]*example.Q, 0, 1)
	curQ := example.Q{}
	s.Item.Data.Qs = append(s.Item.Data.Qs, &curQ)
	fmt.Println(s.Item.Data.Qs)
	s.Item.ItemID = t.Id.Hex()
	s.Item.Data.Type = int32(t.Data.Type)
	s.Item.Data.Stem = t.Data.Stem
	s.Item.Data.Qs[0].Desc = t.Data.Qs[0].Desc
	tans, _ := json.Marshal(t.Data.Qs[0].Ans)
	s.Item.Data.Qs[0].Ans = string(tans)
	for _, v := range t.Data.Qs[0].TagIds {
		tv := v.Hex()
		s.Item.Data.Qs[0].TagIds = append(s.Item.Data.Qs[0].TagIds, tv)
	}
	itemJson, _ := json.Marshal(s)
	s.ItemJSON = string(itemJson)
	fmt.Println(s)
	util.WriteResponse(c, s)
	//c.JSON(200, resp)
}

func mapping(s *example.ItemResp, t model.DbTaggedItem) {
	s.Item = new(example.Item)
	s.Item.Data = new(example.Data)
	//s.Item.Data.Qs = make([]*example.Q, 0, 1)
	curQ := example.Q{}
	s.Item.Data.Qs = append(s.Item.Data.Qs, &curQ)
	fmt.Println(s.Item.Data.Qs)
	s.Item.ItemID = t.Id.Hex()
	s.Item.Data.Type = int32(t.Data.Type)
	s.Item.Data.Stem = t.Data.Stem
	s.Item.Data.Qs[0].Desc = t.Data.Qs[0].Desc
	tans, _ := json.Marshal(t.Data.Qs[0].Ans)
	s.Item.Data.Qs[0].Ans = string(tans)
	for _, v := range t.Data.Qs[0].TagIds {
		tv := v.Hex()
		s.Item.Data.Qs[0].TagIds = append(s.Item.Data.Qs[0].TagIds, tv)
	}
}
