// Code generated by hertz generator.

package example

import (
	"context"
	"time"
	"ttidl1/biz/dal/redis"
	"ttidl1/util"

	"github.com/cloudwego/hertz/pkg/app"
	example "ttidl1/biz/model/h2/example"
)

// RedisSetMethod .
// @router /redis/set [POST]
func RedisSetMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.RedisSetReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	rdb := redis.GetRedisClient()
	rdb.SetCache(req.GetKey(), req.GetValue(), time.Duration(req.GetDur()))
	resp := new(example.RedisResp)
	resp.Msg = "redis set success"
	util.WriteResponse(c, resp)
	//c.JSON(200, resp)
}

// RedisQueryMethod .
// @router redis/query [GET]
func RedisQueryMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.RedisQueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	rdb := redis.GetRedisClient()
	r := rdb.GetCache(req.Key)
	resp := new(example.RedisResp)
	resp.Msg = r
	util.WriteResponse(c, resp)
	//c.JSON(200, resp)
}
