// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package model

import (
	"ttidl1/biz/dal/db"
	"ttidl1/conf"
)

// Injectors from wire.go:

func GetItemDbModel() DbItemModel {
	configServer := conf.NewServerConf()
	mongoClient := db.NewMongoClient(configServer)
	dbItemModel := NewDbItemModel(mongoClient)
	return dbItemModel
}
